name: Deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    env:
      token: ${{ secrets.LINKS_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
    
      - name: Configure SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    
      - name: Fetch deploy target location
        run: |
          link=`curl -sv -H "Authorization: Bearer $token" -H "Accept: application/vnd.github.v3.raw" https://api.github.com/repos/quicknotes-project/links/contents/link.txt`
          proto=$(echo $link | grep :// | sed -e's,^\(.*://\).*,\1,g')
          url=$(echo ${link/$proto/})
          user=$(echo $url | grep @ | cut -d@ -f1)
          hostport=$(echo ${url/$user@/} | cut -d/ -f1)
          host=$(echo $hostport | sed -e 's,:.*,,g')
          port=$(echo $hostport | sed -e 's,^.*:,:,g' -e 's,.*:\([0-9]*\).*,\1,g' -e 's,[^0-9],,g')
          echo "host=$host" >> $GITHUB_ENV
          echo "port=$port" >> $GITHUB_ENV

      - name: Deploy
        run: |
          SWITCHES="-avz --delete --exclude \".*\""
          RSH="ssh -o StrictHostKeyChecking=no -p ${{ env.port }}"
          rsync $SWITCHES -e "$RSH" * pi@${{ env.host }}:~/minimal-openresty-server/
          ssh pi@${{ env.host }} -p ${{ env.port }} "cd ~/minimal-openresty-server; ./reload.sh"
