name: Deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    env:
      token: ${{ secrets.LINKS_TOKEN }}
      key: ${{ secrets.SSH_PRIVATE_KEY }}
      SSH_AUTH_SOCK: /tmp/ssh_agent.sock

    steps:
      - name: Fetch deploy target location
        run: |
          link=`curl -sv -H "Authorization: Bearer $token" -H "Accept: application/vnd.github.v3.raw" https://api.github.com/repos/quicknotes-project/links/contents/link.txt`
          proto=$(echo $link | grep :// | sed -e's,^\(.*://\).*,\1,g')
          url=$(echo ${link/$proto/})
          user=$(echo $url | grep @ | cut -d@ -f1)
          hostport=$(echo ${url/$user@/} | cut -d/ -f1)
          host=$(echo $hostport | sed -e 's,:.*,,g')
          port=$(echo $hostport | sed -e 's,^.*:,:,g' -e 's,.*:\([0-9]*\).*,\1,g' -e 's,[^0-9],,g')
          echo "host=$host" >> $GITHUB_ENV
          echo "port=$port" >> $GITHUB_ENV
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Deploy
        run: |
          ssh-agent -a $SSH_AUTH_SOCK
          echo $key | ssh-add
          SWITCHES="-avz --delete --exclude \".*\""
          RSH="ssh -o StrictHostKeyChecking=no -p ${{ env.port }}"
          rsync $SWITCHES -e "$RSH" * ${{ env.host }}:/home/pi/minimal-openresty-server.copy/

#       - name: Deploy
#         uses: Burnett01/rsync-deployments@5.2.1
#         with:
#           switches: -avz --delete --exclude ".*"
#           path: "*"
#           remote_path: /home/pi/minimal-openresty-server.copy/
#           remote_host: ${{ env.host }}
#           remote_port: ${{ env.port }}
#           remote_user: pi
#           remote_key: ${{ secrets.SSH_PRIVATE_KEY }}
#           rsh: cd ~/minimal-openresty-server; ./reload.sh
